# This file was generated by GoReleaser. DO NOT EDIT.
class Sqsmover < Formula
  desc "AWS SQS Message mover."
  homepage "https://github.com/mercury2269/sqsmover"
  version "0.3.13"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mercury2269/sqsmover/releases/download/v0.3.13/sqsmover_Darwin_x86_64.tar.gz"
    sha256 "6df91157f07cba3fe71b562ca14d700b92c0a27d2d12de3cc5acbea0b04a7b3a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mercury2269/sqsmover/releases/download/v0.3.13/sqsmover_Linux_x86_64.tar.gz"
      sha256 "2790a8c18b83b70c042e1ba966d8f1eb50d3c2ab1ffb0315e5976045e8305523"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mercury2269/sqsmover/releases/download/v0.3.13/sqsmover_Linux_arm64.tar.gz"
        sha256 "45d54e9fffffc73d2893bf673ac65631f001834d3c2fbe443973e0cb0c773beb"
      else
        url "https://github.com/mercury2269/sqsmover/releases/download/v0.3.13/sqsmover_Linux_armv6.tar.gz"
        sha256 "fb3596c4b9ed10af63d86cad6e4370c6f4ef1adcdb68e75906b3e7845b75eeda"
      end
    end
  end

  def install
    bin.install "sqsmover"
  end

  test do
    system "#{bin}/sqsmover -v"
  end
end
