# This file was generated by GoReleaser. DO NOT EDIT.
class Sqsmover < Formula
  desc "AWS SQS Message mover."
  homepage "https://github.com/mercury2269/sqsmover"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mercury2269/sqsmover/releases/download/v0.4.0/sqsmover_Darwin_x86_64.tar.gz"
    sha256 "84e61d30f28819830d81aa4075d8aa371f2ad32768e3ef52b4bb4f17f54ca5be"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mercury2269/sqsmover/releases/download/v0.4.0/sqsmover_Linux_x86_64.tar.gz"
      sha256 "870bd37ed21618d4b429cb60ba10fa17ba6e48bf779df59eea0119b75155745c"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mercury2269/sqsmover/releases/download/v0.4.0/sqsmover_Linux_arm64.tar.gz"
        sha256 "e6c6a6e3a6c49469388ffd7241684c3f5bd4a086419952b0f379080e240393d3"
      else
        url "https://github.com/mercury2269/sqsmover/releases/download/v0.4.0/sqsmover_Linux_armv6.tar.gz"
        sha256 "a8aacb66a740d8e7f7b46bb736d5fcf898661a9dd073cab8cb84c2ac9d9b23f6"
      end
    end
  end

  def install
    bin.install "sqsmover"
  end

  test do
    system "#{bin}/sqsmover -v"
  end
end
